# Generated by Django 5.1.2 on 2024-10-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_bar_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outcome',
            old_name='product',
            new_name='inventory_item',
        ),
    ]
