# Generated by Django 5.1.2 on 2024-10-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_category_alter_product_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outcome',
            old_name='quantity',
            new_name='qty',
        ),
    ]
